config/routes.rb
Rails.application.routes.draw do
  resources :enderecos

  resources :municipes

  get 'municipes/:municipe_id/endereco/new', to: 'enderecos#new_endereco_by_municipe', as: :endereco_new_municipe

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "municipes#index"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/endereco.rb
class Endereco < ApplicationRecord
  belongs_to :municipe

  validates :cep, presence: true
  validates :logradouro, presence: true
  validates :complemento, presence: true
  validates :bairro, presence: true
  validates :cidade, presence: true
  validates :UF, presence: true
 
end

app/models/municipe.rb
class Municipe < ApplicationRecord
#  has_one_attached :imagem

  validate :valida_cpf
  validates :email, presence: true, format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }

  validates :cns, presence: true, format: { with: /\A\d{15}\z/, message: 'inválido' }
  validate :validar_cns

  validates :data_nascimento, presence: true
  validate :data_nascimento_valida

  validates :nome_completo, presence: true

  has_one :endereco

  def self.filtrar(municipes, value)
    # TODO: municipes.data_nascimento = '#{value}' OR    
    # enderecos.UF = '#{value}' OR

    sql = "municipes.nome_completo = '#{value}'"
    sql +=  "OR municipes.cpf = '#{value}' "
    sql +=  "OR municipes.email = '#{value}' "
    sql +=  "OR municipes.cns = '#{value}' "
    sql +=  "OR municipes.telefone = '#{value}' "
    sql +=  "OR enderecos.cep = '#{value}' "
    sql +=  "OR enderecos.logradouro = '#{value}' "
    sql +=  "OR enderecos.complemento = '#{value}' "
    sql +=  "OR enderecos.bairro = '#{value}' "
    sql +=  "OR enderecos.cidade = '#{value}' "
    sql +=  "OR enderecos.cod_ibge = '#{value}'"

    municipes.left_outer_joins(:endereco).where(sql)
  end

  private

  def valida_cpf
    valido = CPF.valid?(cpf)
    errors.add :cpf, 'inválido' if valido.nil?
  end

  def validar_cns
    return if cns.to_s.length == 15

    errors.add :cns, 'inválido'
  end

  def data_nascimento_valida
    return unless data_nascimento.present? && data_nascimento > Date.current

    errors.add :data_nascimento, 'inválida'
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/enderecos_controller.rb
class EnderecosController < ApplicationController
  before_action :set_endereco, only: %i[ show edit update destroy ]

  # GET /enderecos or /enderecos.json
  def index
    @enderecos = Endereco.all
  end

  # GET /enderecos/1 or /enderecos/1.json
  def show
  end

  # GET /enderecos/new
  def new
    @endereco = Endereco.new
  end

  # GET /
  def new_endereco_by_municipe
    @endereco = Endereco.new
    @municipe = Municipe.find(params[:municipe_id])
  end

  # GET /enderecos/1/edit
  def edit
  end

  # POST /enderecos or /enderecos.json
  def create
    @endereco = Endereco.new(endereco_params)

    respond_to do |format|
      if @endereco.save
        format.html { redirect_to endereco_url(@endereco), notice: "Endereco was successfully created." }
        format.json { render :show, status: :created, location: @endereco }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @endereco.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /enderecos/1 or /enderecos/1.json
  def update
    respond_to do |format|
      if @endereco.update(endereco_params)
        format.html { redirect_to endereco_url(@endereco), notice: "Endereco was successfully updated." }
        format.json { render :show, status: :ok, location: @endereco }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @endereco.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /enderecos/1 or /enderecos/1.json
  def destroy
    @endereco.destroy!

    respond_to do |format|
      format.html { redirect_to enderecos_url, notice: "Endereco was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_endereco
      @endereco = Endereco.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def endereco_params
      params.require(:endereco).permit(:municipe_id, :cep, :logradouro, :complemento, :bairro, :cidade, :UF, :cod_ibge)
    end
end

app/controllers/municipes_controller.rb
class MunicipesController < ApplicationController
  before_action :set_municipe, only: %i[show edit update destroy]

  # GET /municipes or /municipes.json
  def index
    @municipes = Municipe.all

    if params[:municipe].present? && municipe_params[:busca].present?
      #@municipes = Municipe.filtrar(@municipes, municipe_params[:busca])
    end

  end

  # GET /municipes/1 or /municipes/1.json
  def show
  end

  # GET /municipes/new
  def new
    @municipe = Municipe.new
  end

  # GET /municipes/1/edit
  def edit
  end

  # POST /municipes or /municipes.json
  def create
    @municipe = Municipe.new(municipe_params)

    respond_to do |format|
      if @municipe.save

        # Criando fila para envio de emails
        UserMailerJob.perform_later(@municipe)

        format.html { redirect_to '/', notice: "Municipe foi criado com sucesso." }
        format.json { render :show, status: :created, location: @municipe }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @municipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /municipes/1 or /municipes/1.json
  def update
    respond_to do |format|
      if @municipe.update(municipe_params)
        format.html { redirect_to municipe_path, notice: "Municipe foi atualizado com sucesso." }
        format.json { render :show, status: :ok, location: @municipe }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @municipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /municipes/1 or /municipes/1.json
  def destroy
  #   @municipe.destroy!

  #   respond_to do |format|
  #     format.html { redirect_to municipes_url, notice: "Municipe foi destruido com sucesso." }
  #     format.json { head :no_content }
  #   end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_municipe
      @municipe = Municipe.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def municipe_params
      params.require(:municipe).permit(:imagem, :nome_completo, :cpf, :cns, :email, 
        :data_nascimento, :telefone, :status, :busca)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/enderecos_helper.rb
module EnderecosHelper
end

app/helpers/municipes_helper.rb
module MunicipesHelper
end

app/views/enderecos/_endereco.html.erb
<div id="<%= dom_id endereco %>">
  
  <% unless @municipe.present? %>
    <p>
      <strong>Municipe:</strong>
      <%= endereco.municipe_id %>
    </p>
  <% end %>

  <p>
    <strong>Cep:</strong>
    <%= endereco.cep %>
  </p>

  <p>
    <strong>Logradouro:</strong>
    <%= endereco.logradouro %>
  </p>

  <p>
    <strong>Complemento:</strong>
    <%= endereco.complemento %>
  </p>

  <p>
    <strong>Bairro:</strong>
    <%= endereco.bairro %>
  </p>

  <p>
    <strong>Cidade:</strong>
    <%= endereco.cidade %>
  </p>

  <p>
    <strong>Uf:</strong>
    <%= endereco.UF %>
  </p>

  <p>
    <strong>Cod ibge:</strong>
    <%= endereco.cod_ibge %>
  </p>

</div>

app/views/enderecos/_form.html.erb
<%= form_with(model: @endereco) do |form| %>
  <% if @endereco.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(@endereco.errors.count, "error") %> prohibited this endereco from being saved:</h2>

      <ul>
        <% @endereco.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :municipe_id, style: "display: block" %>
    <%= form.text_field :municipe_id, value: @municipe.id, readonly: true %>
  </div>

  <div>
    <%= form.label :cep, style: "display: block" %>
    <%= form.text_field :cep %>
  </div>

  <div>
    <%= form.label :logradouro, style: "display: block" %>
    <%= form.text_field :logradouro %>
  </div>

  <div>
    <%= form.label :complemento, style: "display: block" %>
    <%= form.text_field :complemento %>
  </div>

  <div>
    <%= form.label :bairro, style: "display: block" %>
    <%= form.text_field :bairro %>
  </div>

  <div>
    <%= form.label :cidade, style: "display: block" %>
    <%= form.text_field :cidade %>
  </div>

  <div>
    <%= form.label :UF, style: "display: block" %>
    <%= form.text_field :UF %>
  </div>

  <div>
    <%= form.label :cod_ibge, style: "display: block" %>
    <%= form.text_field :cod_ibge %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/enderecos/edit.html.erb
<h1>Editing endereco</h1>

<%= render "form", endereco: @endereco %>

<br>

<div>
  <%= link_to "Show this endereco", @endereco %> |
  <%= link_to "Back to enderecos", enderecos_path %>
</div>

app/views/enderecos/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Enderecos</h1>

<hr/>
<div id="enderecos">
  <% @enderecos.each do |endereco| %>
    <%= render endereco %>
    <p>
      <%= link_to "Show this endereco", endereco %>
    </p>

    <hr/>
  <% end %>
</div><br/>

app/views/enderecos/new.html.erb
<h1>New endereco</h1>

<%= render "form", endereco: @endereco %>

<br>

<div>
  <%= link_to "Back to enderecos", enderecos_path %>
</div>

app/views/enderecos/new_endereco_by_municipe.html.erb
<h1>New municipe</h1>

<%= render "form", municipe: @municipe %>

<br>

<div>
  <%= link_to "Back to municipes", municipes_path %>
</div>

app/views/enderecos/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @endereco %>

<div>
  <%= link_to "Edit this endereco", edit_endereco_path(@endereco) %> |
  <%= link_to "Back to enderecos", enderecos_path %>

  <%= button_to "Destroy this endereco", @endereco, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DesafioOm30</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
   
  </head>

  <body>
    <%= yield %>
  </body>
</html>

<style>
  body{
    padding: 30px;
  }
</style>

app/views/municipes/_form.html.erb
<%= form_with(model: municipe) do |form| %>
  <% if municipe.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(municipe.errors.count, "error") %> prohibited this municipe from being saved:</h2>

      <ul>
        <% municipe.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :imagem, 'Imagem' %>
    <%= form.file_field :imagem %>
  </div> <br/>

  <div>
    <%= form.label :nome_completo, style: "display: block" %>
    <%= form.text_field :nome_completo, class: "form-control" %>
  </div>

  <div>
    <%= form.label :cpf, style: "display: block" %>
    <%= form.text_field :cpf, class: "form-control", onkeypress:"$(this).mask('000.000.000-AA')" %>
  </div>

  <div>
    <%= form.label :cns, style: "display: block" %>
    <%= form.text_field :cns, class: "form-control" %>
  </div>

  <div>
    <%= form.label :email, style: "display: block" %>
    <%= form.text_field :email, class: "form-control" %>
  </div>

  <div>
    <%= form.label :data_nascimento, style: "display: block" %>
    <%= form.date_field :data_nascimento, class: "form-control" %>
  </div>

  <div>
    <%= form.label :telefone, style: "display: block" %>
    <%= form.text_field :telefone, class: "form-control"%>
  </div>

  <div>
    <%= form.label :status, style: "display: block" %>
    <%= form.check_box :status %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/municipes/_municipe.html.erb
<div id="<%= dom_id municipe %>">
  <p>
    <strong>Nome completo:</strong>
    <%= municipe.nome_completo %>
  </p>

  <p>
    <strong>Cpf:</strong>
    <%= municipe.cpf %>
  </p>

  <p>
    <strong>Cns:</strong>
    <%= municipe.cns %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= municipe.email %>
  </p>

  <p>
    <strong>Data nascimento:</strong>
    <%= municipe.data_nascimento %>
  </p>

  <p>
    <strong>Telefone:</strong>
    <%= municipe.telefone %>
  </p>

  <p>
    <strong>Status:</strong>
    <%= municipe.status %>
  </p>

</div>

app/views/municipes/edit.html.erb
<h1>Editando Municipe <%= @municipe.nome_completo %></h1>

<%= render "form", municipe: @municipe %>

<br>

<div>
  <%= link_to "Show this municipe", @municipe %> |
  <%= link_to "Back to municipes", municipes_path %>
</div>

app/views/municipes/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Municipes</h1>

<%= link_to "Novo Municipe", new_municipe_path %>

<hr/>

<%= form_tag('/municipes', method: "GET") do %>
  <%= text_field '', :municipe_busca, {name: 'municipe[busca]', class: "form-control"} %>
  <br/>
  <%= submit_tag("Buscar", class: 'btn btn-primary') %>
  <%= link_to 'Limpar Filtro', '/', class: 'btn btn-primary' %>
<% end %>
<br/>
<hr/>

<div id="municipes">
  <% @municipes.each do |municipe| %>
    <%= render municipe %>
    <p>
      <%= link_to "Mostrar", municipe %>
    </p>
    <hr/>
  <% end %>
</div>

app/views/municipes/new.html.erb
<h1>New municipe</h1>

<%= render "form", municipe: @municipe %>

<br>

<div>
  <%= link_to "Back to municipes", municipes_path %>
</div>

app/views/municipes/show.html.erb
<p style="color: green"><%= notice %></p>

<h3>Municipe</h3>

<%= render @municipe %>

<hr/>
<h4> Endereco </h3>
<%= render partial: 'enderecos/endereco', locals: { endereco: @municipe.endereco} %>

<div>
  <%= link_to "Edit this municipe", edit_municipe_path(@municipe) %> |
  <%= link_to "Back to municipes", municipes_path %>
</div>